#pragma once

// Auto-generated from Instrumentlist.md. Instrument -> ready-to-use prompt fragment.
namespace promptdata
{

struct Instrument { const char* group; const char* name; const char* tags; };

static constexpr Instrument kInstruments[] =
{
    { "Guitars & Plucked", "Classical Guitar", "warm nylon classical guitar, soft rounded fingerpicked attack, quick high-overtone damping" },
    { "Guitars & Plucked", "Steel-String Acoustic Guitar", "bright steel-string acoustic guitar, sharp pick transient, metallic ringing sustain" },
    { "Guitars & Plucked", "12-String Acoustic Guitar", "chorus-like full shimmering twelve-string, doubled string phase interference, beat frequency richness" },
    { "Guitars & Plucked", "Flamenco Guitar", "percussive flamenco guitar, tap plate golpeador body hits, energetic attack" },
    { "Guitars & Plucked", "Dobro Resonator Guitar", "metallic resonator dobro guitar, nasal directional tone, mid-focused frequency peaks" },
    { "Guitars & Plucked", "Solidbody Electric Guitar", "versatile electric guitar, high sustain clean to biting, direct magnetic pickup signal" },
    { "Guitars & Plucked", "Hollowbody Electric Guitar", "woody hollowbody electric guitar, warm feedback-coupled tone, jazz-blues character" },
    { "Guitars & Plucked", "Extended Electric Guitar", "extended range seven-string guitar, deep low frequencies, metal progressive sound" },
    { "Guitars & Plucked", "Electric Bass", "heavy electric bass, deep sub-harmonic foundation, rhythmic harmonic anchor" },
    { "Guitars & Plucked", "Extended Electric Bass", "extended range electric bass, additional low range pitch, harmonic flexibility" },
    { "Guitars & Plucked", "Fretless Electric Bass", "singing fretless bass, smooth microtonal glissando, continuous friction murmur" },
    { "Guitars & Plucked", "Concert Harp", "majestic concert harp, chromatic pedal alterations, complex soundboard resonance" },
    { "Guitars & Plucked", "Celtic Harp", "intimate celtic harp, diatonic warmth, smaller scale resonance" },
    { "Guitars & Plucked", "Concert Zither", "traditional alpine zither, fretboard open strings, warm string resonance" },
    { "Guitars & Plucked", "Mandolin", "bright mandolin, rapid alternating pick tremolo, shimmering double-string attack" },
    { "Guitars & Plucked", "Banjo", "percussive bright banjo, membrane head resonance, cutting bluegrass attack" },
    { "Guitars & Plucked", "Ukulele", "warm cheerful ukulele, fast decay bright overtones, compact hawaiian character" },
    { "Guitars & Plucked", "Bouzouki", "rich greco-oriental bouzouki, sympathetic string resonance, overtone spectrum shimmer" },
    { "Guitars & Plucked", "Kora", "woody pearly west african kora, calabash gourd resonance, bridge harp shimmer" },
    { "Brass", "Trumpet", "brilliant piercing trumpet, radiant bright tone, directional upper harmonics" },
    { "Brass", "Flugelhorn", "soft dark flugelhorn, warmer conical bore, smoothed transient warmth" },
    { "Brass", "Cornet", "compact rounder cornet, medium-conical brass warmth, traditional band tone" },
    { "Brass", "French Horn", "noble velvety french horn, room-filling orchestral tone, wide sound dispersion" },
    { "Brass", "Tenor Horn", "warm full tenor horn, soft brass band intonation, rounded tone character" },
    { "Brass", "Trombone", "flexible glissando trombone, powerful majestic slide tones, continuous pitch bend" },
    { "Brass", "Bass Trombone", "deep bass trombone, hefty foundation low register, big band power" },
    { "Brass", "Euphonium", "soft bulbous euphonium, broad enveloping tone, warm brass character" },
    { "Brass", "Tuba", "deep tuba, sub-acoustic foundation, orchestral bass presence" },
    { "Brass", "Sousaphone", "forward-projecting sousaphone, marching band projection, large bell design" },
    { "Woodwind", "Concert Flute", "silvery clear concert flute, breathy intimate low register, edge-tone air noise" },
    { "Woodwind", "Piccolo Flute", "extremely high piccolo, piercing cutting tone, upper register acoustic energy" },
    { "Woodwind", "Alto Flute", "velvety dark alto flute, lower pitched mellowness, slower transient response" },
    { "Woodwind", "Recorder", "woody baroque recorder, low-overtone clarity, fipple block warmth" },
    { "Woodwind", "Oboe", "nasal piercing oboe, pastoral double-reed, concentrated formant energy" },
    { "Woodwind", "English Horn", "melancholic english horn, warm softened globular bell, lower oboe pitch" },
    { "Woodwind", "Bassoon", "versatile bassoon, humorous elegiac character, rich harmonic double-fold bore" },
    { "Woodwind", "Contrabassoon", "extremely deep contrabassoon, humming reedy foundation, sub-bass orchestral support" },
    { "Woodwind", "Clarinet", "velvety clarinet, radiant highs woody-warm mids, hollow stopped-pipe timbre" },
    { "Woodwind", "Bass Clarinet", "dark rumbling bass clarinet, warm deep tone, aggressive upper buzz" },
    { "Woodwind", "Soprano Saxophone", "radiant soprano saxophone, jazzy oboe-like tone, full harmonic spectrum" },
    { "Woodwind", "Alto Saxophone", "expressive warm alto saxophone, classic jazz flexibility, rounded tone" },
    { "Woodwind", "Tenor Saxophone", "gritty bluesy tenor saxophone, voluminous rock-jazz warmth, vocal-like formant" },
    { "Woodwind", "Baritone Saxophone", "deep buzzing baritone saxophone, smoky bite massive low-end, powerful resonance" },
    { "Folk & Reed", "Duduk", "melancholic duduk, soft apricot wood warmth, resonant chamber intimacy" },
    { "Folk & Reed", "Shawm", "loud penetrating shawm, medieval outdoor projection, aggressive upper harmonics" },
    { "Folk & Reed", "Ney", "smoky atmospheric ney, oriental rim-blown flute, expressive pitch timbre modulation" },
    { "Folk & Reed", "Bagpipes", "continuous drone bagpipes, constant pressure bag chanter, droning resonance" },
    { "Keys & Piano", "Grand Piano", "full dynamic grand piano, overtone-rich soundboard, large low-frequency coupling" },
    { "Keys & Piano", "Baby Grand Piano", "balanced compact baby grand, smaller room tone, reduced bass warmth" },
    { "Keys & Piano", "Upright Piano", "direct intimate upright piano, woody vertical string layout, intimate tone character" },
    { "Keys & Piano", "Prepared Piano", "percussive prepared piano, altered string resonance, sound effect ensemble character" },
    { "Keys & Piano", "Celesta", "ethereal bell-like celesta, pure fundamental metal plates, minimal overtone shimmer" },
    { "Keys & Piano", "Rhodes Piano", "warm bell-like rhodes piano, glassy hard attack, electromechanical tone bars" },
    { "Keys & Piano", "Wurlitzer Electric Piano", "biting wurlitzer piano, midrange-focused rock tone, electrostatic reed character" },
    { "Keys & Piano", "Hohner Clavinet", "percussive funky clavinet, wire-strung rubber hammer, anvil attack character" },
    { "Keys & Piano", "Hammond Organ", "rotating leslie speaker hammond organ, doppler tonewheel chorus, tremolo rotary effect" },
    { "Keys & Piano", "Farfisa Organ", "nasal retro farfisa organ, square-wave transistor aesthetic, 1960s character" },
    { "Keys & Piano", "Analog Synthesizer", "warm analog synthesizer, voltage-controlled oscillators, variable electronic timbres" },
    { "Keys & Piano", "Digital Synthesizer", "glassy digital synthesizer, fm metallic bells, pristine sample playback texture" },
    { "Keys & Piano", "Stage Piano", "transparent stage piano, velocity-sampled acoustic grand, live amplification design" },
    { "Drums & Percussion", "Kick Drum", "deep punchy kick drum, heavy low-frequency pressure, dual head foundation" },
    { "Drums & Percussion", "Snare Drum", "crisp woody snare drum, sympathetic wire buzz, high-frequency crack noise" },
    { "Drums & Percussion", "Toms", "tunable tom drums, wooden shell resonance, melodic decaying pitches" },
    { "Drums & Percussion", "Hi-Hat", "crisp metallic hi-hat, cymbal friction sizzle wash, tight pedal control" },
    { "Drums & Percussion", "Crash Cymbal", "complex crash cymbal, shimmering metallic high-frequency, accent ride definition" },
    { "Drums & Percussion", "Cajon", "wooden cajon, bass-slap split frequency, internal snare character" },
    { "Drums & Percussion", "Congas", "warm tunable congas, thick animal skin resonance, hand-damping flexibility" },
    { "Drums & Percussion", "Djembe", "deep cavernous djembe, goblet-shaped rim slap, wide dynamic range" },
    { "Drums & Percussion", "Tabla", "clear bell-like tabla, pitched harmonic resonance, palm pressure pitch-bend" },
    { "Drums & Percussion", "Darbouka", "crisp popping darbouka, goblet drum snap, resonant bass character" },
    { "Drums & Percussion", "Bodhrán", "deep shamanic bodhrán, frame drum hand modulation, fundamental tone character" },
    { "Drums & Percussion", "Marimba", "warm woody marimba, resonator tube fundamental, rolled mallet swells" },
    { "Drums & Percussion", "Xylophone", "bright dry xylophone, wooden bar attack, pronounced upper overtones" },
    { "Drums & Percussion", "Vibraphone", "vibraphone rotating motor, amplitude vibrato metallic chime, sustained resonance" },
    { "Drums & Percussion", "Glockenspiel", "bright crystalline glockenspiel, high-frequency clarity, piercing metal bars" },
    { "Drums & Percussion", "Handpan", "hypnotic meditative handpan, sustained bell-like tone, sympathetic steel resonance" },
    { "Drums & Percussion", "Steel Pan", "exuberant shimmering steel pan, multi-harmonic caribbean tone, exotic resonance" },
    { "Drums & Percussion", "Shaker", "high-frequency shaker, stochastic noise bursts, rhythmic granular character" },
    { "Drums & Percussion", "Cowbell", "sharp cowbell, focused transient accent, minimal sustain character" },
    { "Wood & Bamboo", "Ethnic Flute", "atmospheric ethnic flute, microtonal breath noise, expressive overblown registers" },
    { "Wood & Bamboo", "Didgeridoo", "continuous didgeridoo drone, vocal tract formant shaping, circular breathing foundation" },
    { "Wood & Bamboo", "Balafon", "raspy balafon, gourd resonator mirliton buzz, wooden bar distortion" },
    { "Wood & Bamboo", "Log Drum", "wooden log drum, dual-pitched tongue slot resonance, warm hollowed timber" },
    { "Wood & Bamboo", "Rainmaker", "cascading rainmaker, seed-filled tube noise, high-frequency waterfall character" },
    { "Metal & Sculpture", "Singing Bowl", "sustained singing bowl, meditative friction tone, slow beating interference modal" },
    { "Metal & Sculpture", "Gong", "chaotic shimmering gong, massive impact overtone clouds, roaring resonance buildup" },
    { "Metal & Sculpture", "Crotales", "piercing bell-like crotales, thick bronze discs, infinite metallic sustain" },
    { "Metal & Sculpture", "Windchimes", "delicate windchime, random micro-melody, high-frequency metal rods" },
    { "Metal & Sculpture", "Tubular Bells", "deep majestic tubular bells, brass tube church bell resonance, long decay sustain" },
    { "Metal & Sculpture", "Anvil", "extreme anvil transient, industrial clanging brightness, high-frequency impact" },
    { "Metal & Sculpture", "Waterphone", "haunting waterphone, whale-like pitch sweep, eerie metallic water resonance" },
    { "Field & Environment", "City Traffic", "broadband city traffic, engine rumble structural squeal, asphalt friction noise" },
    { "Field & Environment", "Train Station", "metallic train station, doppler transit shifts, public space reverberation" },
    { "Field & Environment", "Industrial Construction", "industrial construction impacts, hydraulic hiss grinding, high-energy transients" },
    { "Field & Environment", "Cafe Ambience", "speech babble ambient cafe, cocktail party dynamics, crockery clatter" },
    { "Field & Environment", "Weather Phenomena", "stochastic rain wind noise, explosive thunder shockwave, ice hail impact" },
    { "Field & Environment", "Bodies of Water", "fluid wave sloshing water, hydrodynamic bubble turbulence, droplet resonance" },
    { "Field & Environment", "Animal Fauna", "bird call modulation fauna, tonal biological oscillators, insect high-frequency" },
    { "Field & Environment", "Botanical Textures", "rustling wood botanical texture, creaking mechanical stress, dry organic crackle" },
    { "Field & Environment", "Household Mechanics", "clock tick mechanical, electromechanical hum motor, impulsive door latch" },
    { "Field & Environment", "Paper Textiles", "paper rustling texture, frictional scraping tearing, fibrous rustling noise" },
};
static constexpr int kInstrumentCount = (int) (sizeof (kInstruments) / sizeof (kInstruments[0]));

// Short group names in display order.
static constexpr const char* kInstrumentGroups[] =
{
    "Guitars & Plucked", "Brass", "Woodwind", "Folk & Reed", "Keys & Piano",
    "Drums & Percussion", "Wood & Bamboo", "Metal & Sculpture", "Field & Environment"
};
static constexpr int kInstrumentGroupCount = (int) (sizeof (kInstrumentGroups) / sizeof (kInstrumentGroups[0]));

}
